### ISSUE TITLE
cookieBAR - Timeout for freegeoip

### ISSUE THREAD

**Issue by themichael123** [ToX82/cookie-bar#16] opened 2015-09-09 17:18 UTC
Hi, on every request the following error message is shown in the chrome console:

cookieBAR - Timeout for freegeoip

**Comment by ToX82** [comment] 2015-09-09 19:12
That's a bit of a problem, indeed.
CookieBAR needs freegeoip because the bar should be shown only for the users who are actually subject to the cookie law, the problem is that freegeoip service, while free, is very slow and sometimes it takes 20+ seconds to lookup an ip address.

To avoid such long waiting times, there is a timeout for that request and when the timeout occurs you see  it in the console.

I don't really know how to avoid it... apart of just hiding the message itself, but that's not resolving the issue...

**Comment by themichael123** [comment] 2015-09-09 19:29
Thanks for the prompt reply. From my perspective there are several possibilities:

Simple possible solution: Add an API fallback, e.g. http://www.telize.com/geoip

Complex possible solution: Self host the GEO API on AWS Lambda or some other scalable & cheap service.

**Comment by ToX82** [comment] 2015-09-10 07:20
I didn't know telize, looks like a good alternative to freegeoip. I'll do some testing and if it's actually faster I could make the switch...

**Comment by ToX82** [comment] 2015-09-12 10:16
Fixed using telize. Thank you for the suggestion!

**Closed as completed by ToX82** 2015-09-12 10:16 UTC

**Comment by digitall-it** [comment] 2015-11-17 13:43
//cdn.jsdelivr.net/cookie-bar/1/cookiebar-latest.min.js still seems to refer to 1.5.3.

**Comment by digitall-it** [comment] 2015-11-17 13:51
Seems like the CDN has propagation issues.
